global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'teahouse-services'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['host.docker.internal:8080', 'host.docker.internal:8090', 'host.docker.internal:8091', 'host.docker.internal:8092', 'host.docker.internal:8761']
